### ISSUE TITLE
Uncaught exception 

### ISSUE THREAD

**Issue by dthonon** [dthonon/ExportVN#7]
PHP Fatal error:  Uncaught exception 'OAuthException' with message 'Invalid auth/bad request (got a 403, expected HTTP/1.1 20X or a redirect)' in /home/admind07/ExportVN/ExportJson.php:189
Stack trace:
#0 /home/admind07/ExportVN/ExportJson.php(189): OAuth->fetch('http://www.faun...', Array, 'GET')
#1 /home/admind07/ExportVN/ExportJson.php(247): storeTaxoGroups(Object(LoggerRoot), Array, Object(OAuth))
#2 /home/admind07/ExportVN/ExportJson.php(417): storeObservations(Object(LoggerRoot), Array, Object(OAuth))
#3 {main}

  thrown in /home/admind07/ExportVN/ExportJson.php on line 189

**Comment by dthonon** [comment]
Probably a bug with Ubuntu/Debian, which are not supported.
